# Generated by Django 3.0.3 on 2020-04-30 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=3000, null=True)),
                ('amount', models.CharField(max_length=10, null=True)),
                ('reference', models.TextField(null=True)),
                ('merchant_request_id', models.TextField(null=True)),
                ('CheckoutRequestID', models.TextField(null=True)),
                ('ResultDesc', models.TextField(null=True)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.TextField(null=True)),
                ('organization_balance', models.CharField(max_length=10, null=True)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
    ]
