# Generated by Django 3.0.3 on 2020-04-06 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0005_auto_20200406_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghours',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
