# Generated by Django 3.0.3 on 2020-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0006_auto_20200406_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
