# Generated by Django 3.0.3 on 2020-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0008_stores_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
