# Generated by Django 3.0.3 on 2020-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0009_auto_20200409_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
