# Generated by Django 3.0.3 on 2020-04-09 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0012_stores_admin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='admin_password',
            new_name='admin',
        ),
    ]
