# Generated by Django 3.0.3 on 2020-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0015_auto_20200410_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
