# Generated by Django 3.0.3 on 2020-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
