# Generated by Django 3.0.3 on 2020-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'),
                                            ('archived', 'Archived - not available anymore')], default='available',
                                   max_length=32),
        ),
    ]
