# Generated by Django 3.0.3 on 2020-04-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20200402_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer account'), ('seller', 'seller account')],
                                   default='customer', max_length=32),
        ),
    ]
