# Generated by Django 3.0.3 on 2020-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20200222_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(
                choices=[('Juja', 'Juja and environs'), ('Witeithie', 'Witeithie'), ('Kenyatta road', 'Kenyatta road')],
                default='Juja', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[('admin', 'admin account'), ('customer', 'customer account'), ('staff', 'staff account')],
                default='customer', max_length=32),
        ),
    ]
