# Generated by Django 3.0.3 on 2020-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20200402_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[('admin', 'admin account'), ('customer', 'customer account'), ('seller', 'seller account'),
                         ('staff', 'staff account')], default='customer', max_length=32),
        ),
    ]
