# Generated by Django 3.0.3 on 2020-04-10 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_auto_20200402_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
