# Generated by Django 3.0.3 on 2020-04-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_auto_20200412_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='seller',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='userprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True, serialize=False, to='accounts.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='User Profile',
        ),
    ]
