# Generated by Django 3.0.3 on 2020-04-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_auto_20200412_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_mobile_money_till_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
