# Generated by Django 3.0.3 on 2020-04-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0013_auto_20200412_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alternative_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_money_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
