# Generated by Django 3.0.3 on 2020-04-12 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0019_auto_20200412_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='userprofile_ptr',
            new_name='profile_ptr',
        ),
    ]
