# Generated by Django 3.0.3 on 2020-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mpesa_api', '0003_mpesacallbacks_mpesacalls_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='organization_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='reference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
