# Generated by Django 3.0.3 on 2020-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mpesa_api', '0006_auto_20200417_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
    ]
