# Generated by Django 3.0.3 on 2020-03-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('price_per_unit', models.CharField(max_length=20)),
                ('discounted_price_per_unit', models.CharField(max_length=20)),
                ('egg_less', models.BooleanField(default=True)),
                ('delivery', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('amount_remaining', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField(default=0)),
                ('discounted', models.BooleanField(default=False)),
                ('offer_of_the_day', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Categories')),
            ],
            options={
                'verbose_name_plural': 'inventory items',
                'db_table': 'Inventory',
            },
        ),
    ]
