# Generated by Django 3.0.3 on 2020-02-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200213_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='itemname',
            new_name='item_name',
        ),
    ]
