# Generated by Django 3.0.3 on 2020-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_auto_20200325_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount_remaining',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='discounted_price_per_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price_per_unit',
            field=models.CharField(max_length=20),
        ),
    ]
