# Generated by Django 3.0.3 on 2020-02-13 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200213_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='price_per_kg',
        ),
        migrations.AddField(
            model_name='inventory',
            name='contents',
            field=models.TextField(default=django.utils.timezone.now, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
