# Generated by Django 3.0.3 on 2020-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_auto_20200213_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='contents',
        ),
        migrations.AddField(
            model_name='inventory',
            name='egg_less',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
