# Generated by Django 3.0.3 on 2020-04-02 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0001_initial'),
        ('inventory', '0005_auto_20200325_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sellers.Stores'),
            preserve_default=False,
        ),
    ]
