# Generated by Django 3.0.3 on 2020-02-22 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0006_auto_20200222_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='discounted_price_per_kg',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
