# Generated by Django 3.0.3 on 2020-04-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0006_inventory_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='amount_remaining',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='egg_less',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(upload_to='images/products/'),
        ),
    ]
