# Generated by Django 3.0.3 on 2020-04-06 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0007_auto_20200402_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='hash',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
