# Generated by Django 3.0.3 on 2020-02-22 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0008_inventory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
