# Generated by Django 3.0.3 on 2020-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0008_inventory_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
