# Generated by Django 3.0.3 on 2020-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0009_auto_20200407_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
