# Generated by Django 3.0.3 on 2020-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0009_categories_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='offer_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
