# Generated by Django 3.0.3 on 2020-04-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0010_auto_20200409_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price_per_unit',
            field=models.IntegerField(),
        ),
    ]
