# Generated by Django 3.0.3 on 2020-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0011_auto_20200411_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price_per_unit',
            field=models.PositiveIntegerField(),
        ),
    ]
