# Generated by Django 3.0.3 on 2020-04-11 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0015_auto_20200410_1322'),
        ('inventory', '0012_auto_20200411_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.Stores'),
        ),
    ]
