# Generated by Django 3.0.3 on 2020-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0013_auto_20200411_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
    ]
