# Generated by Django 3.0.3 on 2020-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
