# Generated by Django 3.0.3 on 2020-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
