# Generated by Django 3.0.3 on 2020-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003_auto_20200325_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
