# Generated by Django 3.0.3 on 2020-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_auto_20200325_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
