# Generated by Django 3.0.3 on 2020-04-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0008_stores_hash'),
        ('shop', '0006_auto_20200325_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sellers.Stores'),
            preserve_default=False,
        ),
    ]
