# Generated by Django 3.0.3 on 2020-04-11 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0007_cart_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hash',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
