# Generated by Django 3.0.3 on 2020-04-18 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0016_auto_20200416_1257'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_cart_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_string', models.CharField(max_length=20)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(max_length=20)),
                ('store',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellers.Stores')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
    ]
