# Generated by Django 3.0.3 on 2020-04-19 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0009_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='unit_price',
        ),
    ]
