# Generated by Django 3.0.3 on 2020-04-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0014_auto_20200412_1004'),
        ('shop', '0010_auto_20200419_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Inventory')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Orders')),
            ],
        ),
    ]
