# Generated by Django 3.0.3 on 2020-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0011_auto_20200419_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='time_added',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
