# Generated by Django 3.0.3 on 2020-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0014_orders_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='paid',
        ),
    ]
