# Generated by Django 3.0.3 on 2020-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0015_remove_orders_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
