# Generated by Django 3.0.3 on 2020-04-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0016_orders_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
