# Generated by Django 3.0.3 on 2020-02-22 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
