# Generated by Django 3.0.3 on 2020-03-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.ManyToManyField(blank=True, to='inventory.Inventory'),
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
