# Generated by Django 3.0.3 on 2020-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staffapp', '0002_auto_20200323_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mail', models.EmailField(max_length=300)),
                ('sender_name', models.CharField(max_length=50)),
                ('mail_subject', models.CharField(max_length=50)),
                ('mail_message', models.TextField(max_length=500)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'db_table': 'Messages',
            },
        ),
    ]
