# Generated by Django 3.0.3 on 2020-04-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staffapp', '0004_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
